# dist: xenial
# group: edge???
group: travis_latest
language: cpp
compiler:
  - clang
  # - gcc


env:
  global:
  - PREFIX=/tmp/local
  - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig

  - POPPLER_DATA=poppler-data-0.4.8
  # - TESTDATADIR=/home/travis/build/travis-util/poppler-building/$POPPLER_DATA
  - testdatadir=/home/travis/build/travis-util/poppler-building/test
  
  - GLIB=glib-2.55.0  GLIB_VERSION=2.55


  matrix:
  # - POPPLER=poppler-0.62.0 # Requires:
    # Install libopenjpeg2 before trying to build poppler.  You can also decide
    # to use the internal unmaintained JPX decoder or none at all.
  - POPPLER=poppler-0.60.1
  # - POPPLER=poppler-0.48.0 # Travis libglib2.0-dev is too old
  # - POPPLER=poppler-0.47.0
  # - POPPLER=poppler-0.23.4
  # https://poppler.freedesktop.org/releases.html


addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    # - debian-sid # This is ok for packages with little dependencies like libmount-dev, but not for clang!
    packages:
    # as requested by configure
    # - libopenjp2-7-dev # since Ubuntu 16.04 (libopenjpeg2 for poppler-0.62.0)
    - libopenjpeg-dev
    # - libgtk-3-dev # optional, cannot be taken from debian-sid
    # - libglib2.0-dev # now compiled here
    - libmount-dev # to compile libglib2.0-dev
    # - zlib1g-dev not the right one


before_install:
- apt-cache policy libglib2.0-dev

- make --version # Waiting for version 4.0 to be able to use --output-sync=recurse
# https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html
- pip install --user psutil
- JOBS="$(python -c 'import psutil ; print len(psutil.Process().cpu_affinity())')" # 2 jobs at a time in make

- wget http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/$GLIB.tar.xz # 2.1s
# - wget https://git.gnome.org/browse/glib/snapshot/$GLIB.tar.xz # 35s
- tar --xz --extract --file=$GLIB.tar.xz
- pushd $GLIB
- ./configure --help
- ./configure --prefix=$PREFIX
- make --jobs=$JOBS && make install --jobs=$JOBS
- popd

install:
- wget https://poppler.freedesktop.org/$POPPLER_DATA.tar.gz
- tar --gzip --extract --file=$POPPLER_DATA.tar.gz
- wget https://poppler.freedesktop.org/$POPPLER.tar.xz
- tar --xz --extract --file=$POPPLER.tar.xz
- git clone git://git.freedesktop.org/git/poppler/test
- ls --color
# - printenv TESTDATADIR
# - ls --color $TESTDATADIR
- printenv testdatadir
- cd $POPPLER
- ls --color
- cat INSTALL
- ./configure --help || true # there is a configure in 0.23.4
- mkdir build
- cd build/
- cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX

script:
- make --jobs=$JOBS && make test --jobs=$JOBS && make install --jobs=$JOBS
- cat /proc/loadavg
- echo $JOBS
- ls -rtl $PKG_CONFIG_PATH

# poppler-0.60.1
# poppler-0.48.0
# Needs GLib 2.41 (2.40.2 in Ubuntu 14.04.5 LTS, Trusty Tahr travis_lts)
